### ISSUE TITLE
Tags Handling

### ISSUE THREAD

**Issue by DarkFlamex1** [DarkFlamex1/RoomPlugin#7]
How should we handle tags, because the tags could mess with other plugins. I am planning on making an enum with all the tags. Also for distributionModes? Is it possible to make our own and use those instead of the original ones? Because if you send a message toAll from unity it will send to ALL clients connected to server!

**Comment by Dakkers** [comment]
In the DarkRift Server Plugin tutorial ([link](http://darkrift.ninjapokestudios.co.uk/docs/ServerPluginTutorial.pdf)) it says to create a config file that allows the user to set the tag number, in the case of the server that's the best approach. It may be better to just ask Jamie to give an example of this, though.

**Comment by DarkFlamex1** [comment]
Oh yeah I see, I will check with Jamie too.
